name: deploy-firebase
env:
  DEPLOY_ENV: PRODUCTION

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci
      working-directory: ./nuxt

    - name: build
      run: npm run build
      working-directory: ./nuxt
    
    - name: export
      run: npm run export
      working-directory: ./nuxt
    
    - name: ready to deploy
      run: npm install -g firebase-tools

    - name: deploy
      run: firebase deploy --only hosting --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
